#!/bin/sh

set -e

POWER_CMD="/usr/bin/obmcutil"
GPIO_SET_CMD="/usr/bin/gpioset"
IMAGE_FILE=$1
GPIOJ0=72
GPIOJ1=73

IPMB_OBJ="xyz.openbmc_project.Ipmi.Channel.Ipmb"
IPMB_PATH="/xyz/openbmc_project/Ipmi/Channel/Ipmb"
IPMB_INTF="org.openbmc.Ipmb"
IPMB_CALL="sendRequest yyyyay"
ME_CMD_RECOVER="1 0x2e 0 0xdf 4 0x57 0x01 0x00 0x01"
ME_CMD_RESET="1 6 0 0x2 0"
SPI_DEV="1e630000.spi"
SPI_PATH="/sys/bus/platform/drivers/aspeed-smc"

MTD_MAX=10

set_gpio_value()
{
    $GPIO_SET_CMD gpiochip0 $1=$2
}

set_gpio_to_bmc()
{
    echo "switch bios GPIO to bmc"

    set_gpio_value $GPIOJ0 0
    set_gpio_value $GPIOJ1 1

    return 0
}

set_gpio_to_pch()
{
    echo "switch bios GPIO to pch"

    set_gpio_value $GPIOJ0 1
    set_gpio_value $GPIOJ1 0

    return 0
}

echo "Bios upgrade started at $(date)"

if [ -e "$IMAGE_FILE" ];
then
    echo "Bios image is $IMAGE_FILE"
else
    echo "Bios image $IMAGE_FILE doesn't exist"
    exit 1
fi

#Power off host server.
echo "Power off host server"
$POWER_CMD poweroff
sleep 15
if [ $($POWER_CMD hoststate|awk 'NR==1 {print $3}'|cut -d . -f 6) != "Off" ];
then
    echo "Host server didn't power off"
    echo "Bios upgrade failed"
    exit -1
fi
echo "Host server powered off"

#Set ME to recovery mode
echo "Set ME to recovery mode"
busctl call $IPMB_OBJ $IPMB_PATH $IPMB_INTF $IPMB_CALL $ME_CMD_RECOVER
sleep 5

#Flip GPIO to access SPI flash used by host.
echo "Set GPIO to access SPI flash from BMC used by host"
set_gpio_to_bmc
sleep 5

#Bind spi driver to access flash
echo "bind aspeed-smc spi driver"
echo -n $SPI_DEV > $SPI_PATH/bind
sleep 1

#Flashcp image to device.
for d in $(seq 1 $MTD_MAX) ; do
    if [ -e "/dev/mtd$d" ]; then
        mtd=`cat /sys/class/mtd/mtd$d/name`
        if [ $mtd == "pnor" ]; then
            echo "Flashing bios image to mtd$d..."
            flashcp -v $IMAGE_FILE /dev/mtd$d
            if [ $? -eq 0 ]; then
                echo "bios updated successfully..."
            else
                echo "bios update failed..."
            fi
            break
        fi
        echo "$d is not a pnor device"
    fi
    echo "$d not available"
done

#Unbind spi driver
sleep 1
echo "Unbind aspeed-smc spi driver"
echo -n $SPI_DEV > $SPI_PATH/unbind
sleep 10

#Flip GPIO back for host to access SPI flash
echo "Set GPIO $GPIO back for host to access SPI flash"
set_gpio_to_pch
sleep 5

#Reset ME to boot from new bios
echo "Reset ME to boot from new bios"
busctl call $IPMB_OBJ $IPMB_PATH $IPMB_INTF $IPMB_CALL $ME_CMD_RESET
sleep 10

#Power on server
echo "Power on server"
$POWER_CMD chassison
sleep 5

# Retry to power on once again if server didn't powered on
if [ $($POWER_CMD hoststate|awk 'NR==1 {print $3}'|cut -d . -f 6) != "Running" ];
then
    sleep 5
    echo "Powering on server again"
    $POWER_CMD chassison
fi