#!/bin/sh

set -e

POWER_CMD="/usr/bin/obmcutil"
REGISTER_CMD="/sbin/devmem"
IMAGE_FILE=$1
HW_STRAP_REGISTER=0x1e6e2070
HW_STRAP_CLEAR_REGISTER=0x1e6e207C
SPI_MODE_bit_1=0x00001000
SPI_MODE_bit_2=0x00002000

SPI_DEV="1e630000.spi"
SPI_PATH="/sys/bus/platform/drivers/aspeed-smc"

MTD_MAX=10

set_ast2500_register()
{
    original_register=`$REGISTER_CMD $1`
    $REGISTER_CMD $1 32 $(($original_register|$2))
}

echo "Bios upgrade started at $(date)"

if [ -e "$IMAGE_FILE" ];
then
    echo "Bios image is $IMAGE_FILE"
else
    echo "Bios image $IMAGE_FILE doesn't exist"
    exit 1
fi

#Power off host server.
echo "Power off host server"
$POWER_CMD poweroff
sleep 15
if [ $($POWER_CMD hoststate|awk 'NR==1 {print $3}'|cut -d . -f 6) != "Off" ];
then
    echo "Host server didn't power off"
    echo "Bios upgrade failed"
    exit -1
fi
echo "Host server powered off"

echo "Set SPI to master mode"
set_ast2500_register $HW_STRAP_CLEAR_REGISTER $SPI_MODE_bit_2
set_ast2500_register $HW_STRAP_REGISTER $SPI_MODE_bit_1
sleep 1

#Bind spi driver to access flash
echo "bind aspeed-smc spi driver"
echo -n $SPI_DEV > $SPI_PATH/bind
sleep 1

#Flashcp image to device.
for d in $(seq 1 $MTD_MAX) ; do
    if [ -e "/dev/mtd$d" ]; then
        mtd=`cat /sys/class/mtd/mtd$d/name`
        if [ $mtd == "pnor" ]; then
            echo "Flashing bios image to mtd$d..."
            flashcp -v $IMAGE_FILE /dev/mtd$d
            if [ $? -eq 0 ]; then
                echo "bios updated successfully..."
            else
                echo "bios update failed..."
            fi
            break
        fi
        echo "$d is not a pnor device"
    fi
    echo "$d not available"
done

#Unbind spi driver
sleep 1
echo "Unbind aspeed-smc spi driver"
echo -n $SPI_DEV > $SPI_PATH/unbind
sleep 10

echo "Set SPI to Pass-through mode"
set_ast2500_register $HW_STRAP_REGISTER $(($SPI_MODE_bit_1|$SPI_MODE_bit_2))
sleep 1

#Power on server
echo "Power on server"
$POWER_CMD chassison
sleep 5

# Retry to power on once again if server didn't powered on
if [ $($POWER_CMD hoststate|awk 'NR==1 {print $3}'|cut -d . -f 6) != "Running" ];
then
    sleep 5
    echo "Powering on server again"
    $POWER_CMD chassison
fi